name: Step 2, Commit changes

# This step triggers after the learner pushes to `fix-typo`.
# This workflow updates from step 2 to step 3.

# This will run every time the learner makes a push to the `fix-typo` branch.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - fix-typo

env:
  is_typo_fixed: ${{ false }}

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_push_changes:
    name: On push changes
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 2.
    # 3. The event is a branch.
    # 4. The branch name is `fix-typo`.
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 2
          && github.ref_type == 'branch'
          && github.ref_name == 'fix-typo' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment variable if fixed
        run: |
          if grep -q Python "./website.md"; then
            echo "is_typo_fixed=true" >> $GITHUB_ENV
          else
            echo "is_typo_fixed=false" >> $GITHUB_ENV
          fi

      - name: Update to step 3
        if: ${{ env.is_typo_fixed == 'true' }}
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: fix-typo
